dist: trusty
sudo: required
language: python
cache: pip
env:
- FLASK_APP=run.py FLASK_DEBUG=1
python:
  - "3.6.1"
addons:
  apt:
    packages:
      - sqlite3
  sonarcloud:
    organization: "gbasood-github"
    token:
      secure: 1bdcd8624f3d753e1d2e605ec5159786ce92a4d4
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - flask test
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
